export const metadata = {
  title: "Amr - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-dark">{children}</body>
    </html>
  );
}
