import "../../globals.css";

export const metadata = {
  title: "Amr - Works",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="projectsPage py-8">
      <div className="container mx-auto">{children}</div>
    </div>
  );
}
